#pragma once

// From glfw3.h
#define MIRRA_MOUSE_BUTTON_1         0
#define MIRRA_MOUSE_BUTTON_2         1
#define MIRRA_MOUSE_BUTTON_3         2
#define MIRRA_MOUSE_BUTTON_4         3
#define MIRRA_MOUSE_BUTTON_5         4
#define MIRRA_MOUSE_BUTTON_6         5
#define MIRRA_MOUSE_BUTTON_7         6
#define MIRRA_MOUSE_BUTTON_8         7
#define MIRRA_MOUSE_BUTTON_LAST      MIRRA_MOUSE_BUTTON_8
#define MIRRA_MOUSE_BUTTON_LEFT      MIRRA_MOUSE_BUTTON_1
#define MIRRA_MOUSE_BUTTON_RIGHT     MIRRA_MOUSE_BUTTON_2
#define MIRRA_MOUSE_BUTTON_MIDDLE    MIRRA_MOUSE_BUTTON_3